CREATE TABLE BOARD(
	NUM NUMBER NOT NULL PRIMARY KEY, --일련번호
	WRITER VARCHAR2(50) NOT NULL,
	SUBJECT VARCHAR2(50) NOT NULL,
	PASSWD VARCHAR2(60) NOT NULL,
	REG_DATE DATE DEFAULT SYSDATE,
	HIT NUMBER DEFAULT 0,
	GROUP_NUM NUMBER NIT NULL,
	RE_ORDER NUMBER NOT NULL,
	RE_DEPTH NUMBER NOT NULL,
	CONTENTS CLOB NOT NULL,
	IP VARCHAR2(30) NOT NULL,
	FILENAME VARCHAR2(200),
	FILESIZE NUMBER DEFAULT 0,
	DOWN NUMBER DEFAULT 0
);

INSERT INOT BOARD (NUM, WRITER, SUBJECT, PASSWD, GROUP_NUM, RE_ORDER, RE DEPTH, CONTENTS, IP, FILENAME) VALUES
((SELECT NVL(MAX(NUM)+1, 1) FROM BOARD), 'KIM', '제목', '1234', 
(SELECT NVL(MAX(NUM)+1,1) FROM BOARD), 1, 0, '내용', '127.0.0.1','-');
SELECT * FROM BOARD;

CREATE TABLE BOARD_COMMENT(
	COMMENT_NUM NUMBER NOT NULL PRIMARY KEY,
	BOARD_NUM NUMBER NOT NULL REFERENCES BOARD(NUM),
	WRITER VARCHAR2(50) NOT NULL,
	CONTENTS CLOB NOT NULL,
	REG_DATE DATE DEFAULT SYSDATE
);

INSERT INTO BOARD_COMMENT
(COMMENT_NUM, BOARD_NUM, WRITER, CONTENTS) VALUES
((SELECT NVL(MAX(COMMENT_NUM)+1, 1) FROM BOARD_COMMENT), 1, 'KIM', '댓글...');
SELECT * FROM BOARD_COMMENT;
COMMIT;