SELECT * FROM FLOWER;
/*SELECT FLOWERNAME, FLOWERCOLOR, FLOWERPRICE FROM FLOWER;*/
--추가: 부모와 자식중 부모 테이블에 값을 먼저추가해야 한다.
--삭제: 부모와 자식 중 자식 테이블에서 참조하는 값들을 먼저 삭제해야한다.
--부모: ◇ / 자식 ● 잘확인해야한다.

INSERT INTO FLOWER
(FLOWERNAME, FLOWERCOLOR, FLOWERPRICE)
VALUES('장미', 'RED', 3000);

INSERT INTO FLOWER
(FLOWERNAME, FLOWERCOLOR, FLOWERPRICE)
VALUES('해바라기', 'YELLOW', 5000);

INSERT INTO FLOWER
(FLOWERNAME, FLOWERCOLOR, FLOWERPRICE)
VALUES('할미꽃', 'WHITE', 9000);

--WHERE절으로 삭제: 자식이 값을 참조하고 있으면 오류출력
DELETE FROM FLOWER
WHERE FLOWERNAME = "장미";

SELECT * FROM POT;
INSERT INTO POT
(POTID, POTCOLOR, POTSHAPE, NAME)
VALUES('20210505001', 'WHITE', '물레방아', '장미');

INSERT INTO POT
(POTID, POTCOLOR, POTSHAPE, NAME)
VALUES('20210505002', 'BLACK', '타원형', '해바라기');

INSERT INTO POT
(POTID, POTCOLOR, POTSHAPE, NAME)
VALUES('20210505003', 'RED', '사각형', '할미꽃');

DELETE FROM POT
WHERE NAME = "장미";

--DELETE와 TRUNCATE
--DELETE는 복구가 가능하다.
--TRUNCATE는 복구가 불가능하다.

UPDATE POT
SET POTCOLOR = 'WHITE'
WHERE NAME = '할미꽃' AND POTSHAPE = '타원형';