CREATE TABLE TBL_CAR(
	ID NUMBER,
	BRAND VARCHAR2(200),
	COLOR VARCHAR2(150),
	PRICE NUMBER(10),
	CONSTRAINT CAR_PK PRIMARY KEY(ID)
);

SELECT * FROM TBL_CAR;
ALTER TABLE TBL_CAR MODIFY BRAND NOT NULL;
ALTER TABLE TBL_CAR DROP CONSTRAINT SYS_C007280;
-- SYS_C007280는 변하는 값으로 TBL_CAR테이블 더블클릭 -> CONSTRAINT -> BRAND 값 더블클릭 -> NAME값 

DROP TABLE TBL_CAR;

SELECT * FROM PLAYER WHERE "POSITION"  IS NULL;
SELECT * FROM PLAYER WHERE "POSITION"  IS NOT NULL;
---------------------------------------------------------------------------------
SELECT * FROM TBL_CAR;

ALTER TABLE TBL_CAR MODIFY BRAND NOT NULL;

INSERT INTO TBL_CAR VALUES(001, '벤츠', '회색', 35000);
INSERT INTO TBL_CAR VALUES(002, '아우디', NULL, 35000);
--INSERT INTO TBL_CAR VALUES(002, NULL, '회색', 35000); / 오류발생

--PLAYER 테이블에서 POSITION이 NULL인 선수검색
SELECT * FROM PLAYER WHERE "POSITION" IS NULL;

--PLAYER 테이블에서 POSITION이 NULL이면 '미정'으로 결과 출력하기
SELECT NVL ("POSITION", '미정') FROM PLAYER WHERE "POSITION" IS NULL;
SELECT PLAYER_NAME "선수이름", NVL("POSITION", '미정') 포지션 FROM PLAYER;

SELECT PLAYER_NAME "선수이름", NVL2("POSITION", '확정', '미정') AS 포지션 FROM PLAYER;

--PLAYER 테이블에서 NATION이 NULL이 아니면 등록, NULL이면 미등록으로 변경
SELECT PLAYER_NAME "선수이름", NVL2(NATION, '등록', '미등록') "국가등록여부" FROM PLAYER;