CREATE TABLE TBL_CAR(
	ID NUMBER,
	BRAND VARCHAR2(200),
	COLOR VARCHAR2(150),
	PRICE NUMBER(10),
	CONSTRAINT CAR_PK PRIMARY KEY(ID)
);

SELECT * FROM TBL_CAR;
ALTER TABLE TBL_CAR MODIFY BRAND NOT NULL;
ALTER TABLE TBL_CAR DROP CONSTRAINT SYS_C007280;
-- SYS_C007280는 변하는 값으로 TBL_CAR테이블 더블클릭 -> CONSTRAINT -> BRAND 값 더블클릭 -> NAME값 

DROP TABLE TBL_CAR;

SELECT * FROM PLAYER WHERE "POSITION"  IS NULL;
SELECT * FROM PLAYER WHERE "POSITION"  IS NOT NULL;