--GROUP BY: ~별(예: 포지션 별 평균키 불러오기)
--SELECT ??? FROM ???
--WHERE 조건식
--GROUP BY 컬럼명
--HAVING 조건식 

--PLATER 테이블에서 포지션 검색
SELECT "POSITION" FROM PLAYER
GROUP BY "POSITION"
HAVING "POSITION" IS NOT NULL;

--WHERE절에서 조건을 처리할수 있다면 반드시 WHERE절에서 먼저 처리해준다.
SELECT "POSITION" FROM PLAYER
WHERE "POSITION" IS NOT NULL
GROUP BY "POSITION";

--PLAYER 테이블에서 몸무게가 80이상인 선수들의 평균 키가 180이상인 포지션 검색
-- SELECT * FROM PLAYER -- *는 모두 불러오는 것으로 POSITION 뿐만아니라 NAME 등 다른것도 포함되어 포지션에 그룹화할수 없다.
SELECT "POSITION", AVG(HEIGHT), MIN(WEIGHT) FROM PLAYER
WHERE WEIGHT >= 80 
GROUP BY "POSITION"
HAVING AVG(HEIGHT) >= 180;
----------------------------------------------------------------------------

--SUB QUERY
--FROM절 : IN LINE VIEW
--SELECT절 : SCALAR
--WHERE절 : SUB QUERY

--PLAYER 테이블에서 TEAM_ID가 'K01' 인 선수 중 POSITION 이 GK인 선수
SELECT * FROM 
(
	SELECT * FROM PLAYER WHERE TEAM_ID = 'K01'
)
WHERE "POSITION" = 'GK';

--PLAYER 테이블에서 평균 키보다 작은 선수 검색 / WHERE절에서 사용
SELECT AVG(HEIGHT) FROM PLAYER; -- 평균 값: 179.3 
SELECT * FROM PLAYER
WHERE HEIGHT < (SELECT AVG(HEIGHT)FROM PLAYER);

-- PLAYER 테이블에서 전체평균 키와 포지션별 평균 키 구하기
SELECT "POSITION", AVG(HEIGHT), (SELECT AVG(HEIGHT) FROM PLAYER) FROM PLAYER
WHERE "POSITION" IS NOT NULL
GROUP BY "POSITION";

--CASE문으로 변경
SELECT
	ROUND(AVG(CASE "POSITION" WHEN 'GK' THEN HEIGHT END), 2) AS GK,
	ROUND(AVG(CASE "POSITION" WHEN 'GK' THEN HEIGHT END), 2) AS DK,
	AVG(CASE "POSITION" WHEN 'GK' THEN HEIGHT END) AS FW,
	AVG(CASE "POSITION" WHEN 'GK' THEN HEIGHT END) AS MF,
	AVG(HEIGHT) AS "전체 평균"
FROM PLAYER;

--PLAYER테이블에서 NICKNAME이 NULL인 선수들은 정태민 선수의 닉네임으로 바꾸기
SELECT * FROM PLAYER WHERE PLAYER_NAME = '정태민';
UPDATE PLAYER
SET NICKNAME = (SELECT NICKNAME FROM PLAYER WHERE PLAYER_NAME = '정태민')
WHERE NICKNAME IS NULL;

SELECT * FROM PLAYER WHERE NICKNAME = '킹카';

--EMPLOYEES 테이블에서 평균 급여보다 낮은 사원들의 급여를 10% 인상
SELECT AVG(SALARY) FROM EMPLOYEES;
SELECT * FROM EMPLOYEES
WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES);

UPDATE EMPLOYEES
SET SALARY = SALARY * 1.1
WHERE SALARY < (SELECT AVG(SALARY) FROM EMPLOYEES);
SELECT * FROM EMPLOYEES;
