SELECT * FROM PLAYER ORDER BY PLAYER_ID DESC;

SELECT I.INDEX_NAME FROM USER_IND_COLUMNS I
WHERE TABLE_NAME = 'PLAYER';

SELECT /*+ INDEX_DESC(PLAYER PLAYER_PK) */ * FROM PLAYER;
SELECT /*+ INDEX(PLAYER PLAYER_PK) */ * FROM PLAYER;
--/*D와 +를 붙여서 작성해야한다. /*+