-- PLAYER 테이블에서 팀별 최대 몸무게인 선수의 TEAM_ID, REGION_NAME, PLAYER_NAME, WEIGHT검색하고
-- WHERE IN 사용하기

-- 선수 검색
SELECT * FROM TEAM;
--SELECT TEAM_ID, REGION_NAME, PLAYER_NAME, WEIGHT
--FROM PLAYER P JOIN TEAM T
--ON P.TEAM_ID = T.TEAM_ID;

--PLAYER 테이블에서 팀별 최대 몸무게 검색
SELECT TEAM_ID, MAX(WEIGHT) FROM PLAYER
GROUP BY TEAM_ID
ORDER BY 1;

--선수 중 최대 몸무게 검색
SELECT P.TEAM_ID, REGION_NAME, PLAYER_NAME, WEIGHT
FROM PLAYER P JOIN TEAM T
ON P.TEAM_ID = T.TEAM_ID
AND (P.TEAM_ID, P.WEIGHT) IN (SELECT TEAM_ID, MAX(WEIGHT) FROM PLAYER GROUP BY TEAM_ID);

--DEPT테이블의 LOC별 평균 급여를 반올림한 값과 각 LOC별 SAL 총 합을 조회
SELECT * FROM DEPT;
SELECT * FROM EMP;

SELECT D.LOC, ROUND(AVG(E.SAL)), SUM(E.SAL)
FROM DEPT D JOIN EMP E
ON D.DEPTNO = E.DEPTNO
GROUP BY D.LOC;

--EMP 테이블에서 HIREDATE가 FORD의 입사년도와 같은 사원 전체 정보 조회
SELECT * FROM EMP;
-- HIREDATE에서 문자열중 FORD와 같은 년도를 가지고오는데 SUBSTR로 1~4자리까지만 불러오고 전체출력
WHERE TO_CHAR(HIREDATE, 'YYYY-MM-DD') LIKE (SELECT SUBSTR(TO_CHAR(HIREDATE, 'YYYY-MM-DD'), 1, 4) FROM EMP WHERE ENAME = 'FORD') || '%';

--AVG 함수를 쓰지않고 PLAYER 테이블에서 선수들의 평균 키 구하기(NULL 미포함)
SELECT SUM(HEIGHT) / COUNT(HEIGHT) FROM PLAYER; --SUM(전체) / COUNT 
SELECT AVG(HEIGHT) FROM PLAYER; --NULL포함 출력
SELECT AVG(NVL(HEIGHT, 170)) FROM PLAYER; --NULL인 선수들을 키 170으로 변경후 출력

SELECT * FROM PLAYER WHERE HEIGHT IS NULL;