CREATE OR REPLACE PROCEDURE GET_GRADE
(
	SCORE NUMBER 
)
IS
	GRADE VARCHAR2(5); 
BEGIN
	IF SCORE >= 90 THEN GRADE := 'A';
	ELSIF SCORE >= 80 THEN GRADE := 'B';
	ELSIF SCORE >= 70 THEN GRADE := 'C';
	ELSIF SCORE >= 60 THEN GRADE := 'D';
	ELSE GRADE := 'F';
	END IF;
	DBMS_OUTPUT.ENABLE;
	DBMS_OUTPUT.PUT_LINE('당신의 점수: '||SCORE||'점'||CHR(10)||'학점: '||GRADE)
END;

CALL GET_GRADE(80);
CALL GET_GRADE(100);
-----------------------------------------------------------------------------
SELECT * FROM JOBS;
CALL MY_NEW_JOB_PROC('IT', 'Developer', 5000, 20000);

CREATE OR REPLACE PROCEDURE HR.DEL_JOB_PROC
(
	P_JOB_ID IN JOBS.JOB_ID%TYPE
)
IS
	CNT NUMBER := 0;
BEGIN
	SELECT COUNT(JOB_ID) INTO CNT
	FROM JOBS WHERE JOB_ID = P_JOB_ID;
	IF CNT != 0 THEN
		DELETE FROM JOBS
		WHERE JOB_ID = P_JOB_ID;
		DBMS_OUTPUT.ENABLE;
		DBMS_OUTPUT.PUT_LINE('DELETE ALL DONE ABOUT '||' '||P_JOB_ID);
	ELSE
		DBMS_OUTPUT.ENABLE;
		DBMS_OUTPUT.PUT_LINE('NOT EXIST '||' '||P_JOB_ID);
	END IF;
END;
	CALL DEL_JOB_PROC('IT');