CREATE SEQUENCE SEQ_USER;


CREATE TABLE TBL_USER(
	NUM NUMBER PRIMARY KEY,
	ID VARCHAR2(1000),
	NAME VARCHAR2(1000),
	PASSWORD VARCHAR2(1000),
	GENDER VARCHAR2(100),
	ZIPCODE VARCHAR2(100),
	ADDRESS VARCHAR2(1000),
	ADDRESS_DETAIL VARCHAR2(1000),
	ADRESS_ETC VARCHAR2(1000)
);

SELECT * FROM TBL_USER;


DELETE FROM TBL_USER WHERE NAME<> '±è±¤µ¿';
DELETE FROM TBL_USER WHERE NAME IS NULL;